# Generated by Django 4.0.8 on 2022-11-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_created_by_topic_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
